### ISSUE TITLE
On board view, the first swimlane is showed below columns

### ISSUE THREAD

**Issue by djalmaoliveira** [kanboard/kanboard#2850] opened 2016-11-29 15:35 UTC
### Expected behaviour

All columns should be placed below swimlane name.

### Actual behaviour

the first swimlane is showed below columns.

### Steps to reproduce

1. create a project;
2. in setting / swinlane / add new swimlane;
3. go to board view

### Configuration
Application version: 1.0.34
PHP version: 5.5.9-1ubuntu4.14
PHP SAPI: apache2handler
OS version: Linux 4.4.0-47-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36

**Comment by fguillot** [comment] 2016-11-30 01:01
Duplicate of #2575

**Closed by fguillot** 2016-11-30 01:01 UTC
Labels: duplicate
