### ISSUE TITLE
Feature Request: Limit what notifications are sent based on the type of change

### ISSUE THREAD

**Issue by manuvarkey** [kanboard/kanboard#3736] opened 2018-02-24 06:27 UTC
Is there a way to limit what notifications are sent based on the type of change made in Kanboard ? Sending notifications for all new tasks, new subtasks, new comments, editing tasks, etc can get pretty spamming for certain projects.

**Comment by fguillot** [comment] 2018-02-26 22:23
Duplicate of #3186

**Closed by fguillot** 2018-02-26 22:23 UTC
