### ISSUE TITLE
Bad Tooltip behavior

### ISSUE THREAD

**Issue by Kantime** [kanboard/kanboard#3915] opened 2018-06-16 10:01 UTC
### Actual behaviour

Version 1.2.5 (since 1.2.4): tooltips are persistent when hovering with the mouse.

### Expected behaviour

Come back to version 1.2.3 behavior.

**Comment by fguillot** [comment] 2018-07-04 17:39
Duplicate of #3932

**Closed by fguillot** 2018-07-04 17:39 UTC
