### ISSUE TITLE
Time traking for tasks like in sub tasks.

### ISSUE THREAD

**Issue by Danoposada** [kanboard/kanboard#2068] opened 2016-03-29 21:10 UTC
Well, this is more a question than an issue, and I'm not really sure where to ask or look for guidance for this, so I apologize in advance if this is not the place (I would really appreciate it if you point me in the right direction if that is the case).

So, here's the situation: we want to be able to be able to track time for tasks the same way it's tracked for subtaks; meaning, we want to be able to hit a button, change the task to "in progress" status and let it log the spent time automatically, without having to update it manually ourselves.

Another solution for us would be to be able to automatically create a default subtask for each task created just for the purpose of time tracking.

I was thinking it would be posible to write an automatic action plugin that creates a subtask whenever a new task is created.  I'm thinking that the "Automatic Action Plugin Example" could be edited to do what we want. The main problem for me is that my experience in coding goes as far as making small edits to lisp routines for AutoCAD, and nothing more. I'm neither a coder nor I know anything about php.

So, here are my questions:
Is it posible to make subtasks through an automatic action plugin at the moment?
If so, can you give some pointers on how to go about that?
I'm thinking I could do a crash course on php; you know, just enough to make this.
Would it be too difficult?

Thanks.

**Comment by fguillot** [comment] 2017-11-24 18:37
Duplicate of #1885

**Closed by fguillot** 2017-11-24 18:37 UTC
Labels: feature request
