### ISSUE TITLE
Progress and notes not updating

### ISSUE THREAD

**Issue by scottyjustknows** [kanboard/kanboard#4190] opened 2019-05-14 00:01 UTC
### Actual behaviour
When you hover your mouse over either the notes icon or percentage progress indicator for each task, that shows up correctly. However to view the same indicator in another task, you must first click an empty/non-active area in the browser window for the currently displayed progress details to disappear before the same information can be shown for any new task.

Perhaps this is a time-out issue for the previous information? 

Thank you for looking into this.

### Expected behaviour
When your mouse is not hovering over either the notes icon or progress indicator of any task, there should not be any notes or progress indicators open.

### Steps to reproduce
1. Hover mouse over notes or percentage icon of an existing or new task
2. The relevant information appears
3. Move the pointer away from that icon or the information window that appears
4. The information window that appears will remain until you click in a non-active area of the application

### Configuration
- Kanboard version: 1.2.9 / master.702379a55093aa62bae7dcd49a657397a21fd6b5
- Database type and version: sqlite, version 3.11.0
- PHP version: 7.0.33-0ubuntu0.16.04.4
- OS: Ubuntu 16.04.1
- Browser: Firefox 66.0.5 and Chrome 74
- Total Tasks: 288
- Database size: 14.59M

**Comment by scottyjustknows** [comment] 2019-05-14 00:19
This issue also happens on Chrome 74.

**Comment by fguillot** [comment] 2019-06-04 03:13
Looks like a duplicate of #3932.

**Comment by scottyjustknows** [comment] 2019-06-04 14:21
Frederic, thank you, I missed that. Will try the patch mentioned there

**Comment by fguillot** [comment] 2020-01-06 04:58
Duplicate of #3932.

**Closed by fguillot** 2020-01-06 04:58 UTC
