### ISSUE TITLE
Swimlanes height is wrong sometimes

### ISSUE THREAD

**Issue by DebianRoxx** [kanboard/kanboard#4077] opened 2018-11-22 13:16 UTC
### Actual behaviour

Sometimes, board display the swimlanes with a lot of blank space.
Just press F5 and it's gone.

### Expected behaviour

The height of swimlanes must not have blank space.

### Steps to reproduce

No steps to reproduce it, it's random.

XPath concerned is : /html/body/section/section/div[2]/table/tbody/tr[3]/td[2]/div[1]
CSS Path concerned is : html body section.page section#main div#board-container table#board.board-project tbody tr.board-swimlane.board-swimlane-tasks-28 td.board-column-86 div.board-task-list.board-column-expanded.sortable-column.ui-sortable

In browser development tools, min-height is not the same before and after F5.
Before : 1850 px ;
After : 378 px ;

I think problem is in assets/js/src/BoardDragAndDrop.js:53.

### Screenshots

No screenshots needed.
### Logs

No logs needed.

### Configuration

- Kanboard version: 1.2.6 commit 1268c0023d7085fb4d960b869bf79ef0ade0d212
- Database type and version: MariaDB 10.1.26
- PHP version: 7.0.30-0+deb9u1
- OS: Debian GNU/Linux 9.5 (stretch)
- Browser: Firefox 63.0.1 (64 bits) / xUbuntu

**Comment by ChangePlaces** [comment] 2019-05-24 11:54
I used to have this happen, but since upgrading to a newer version a while back, it doesn't happen any more.

**Comment by SladeP** [comment] 2019-11-18 07:58
@DebianRoxx looks like this got fixed in a future version. Can you still reproduce it or close this issue?

**Closed** 2019-12-16 04:43 UTC
