### ISSUE TITLE
Subtasks not visible on board

### ISSUE THREAD

**Issue by darkocobe** [kanboard/kanboard#2552] opened 2016-08-05 08:45 UTC
### Expected behavior

When sub tasks are created and assigned to different project members they should be able to see them in dashboard, board, calendar ...
### Actual behavior

Once sub task is assigned to you and you are not owner of the parent task you can't see the assigned sub task on your board anymore. This was working in the previous version once we upgraded to 1.0.31 is not working anymore. You can still see the sub tasks into your Dashboard but not board anymore. 
### Steps to reproduce
1. Create task with multiple sub tasks
2. Assign the  to different project members
3. Check the board of these members if you can see the sub tasks assigned 
### Configuration
- Kanboard version: 1.0.31
- Database type and version:  postgres
- PHP version: 7.0.0
- OS: Windows NT 6.3
- Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by Chaosmeister** [comment] 2016-08-10 09:09
I'm unable to reproduce this.

I can still see my assigned subtasks if the parenttask is unassigned or assigned to someone else.

using:
Application version: 1.0.32
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by darkocobe** [comment] 2016-08-17 07:54
Below in pictures you can see what we experience. Main task assigned to my colleague and two sub-tasks for me and other colleague (first picture). Once I open board filtered by his username I see the parent task. 
I open my board I do not see any sub-task in Grooming column (picture two). If I go to my dashboard obviously I have lot of sub-tasks including this one but not visible on boards (picture three). 

I see you tested on newer version can be related to some upgrade problems when we upgraded to 1.0.31? If you can't reproduce what will be your suggestion for fix?

![kanboard3](https://cloud.githubusercontent.com/assets/15818492/17728479/b7e20366-645f-11e6-9393-3babed416d75.PNG)
![kanboard1](https://cloud.githubusercontent.com/assets/15818492/17728478/b7e0bf74-645f-11e6-8da1-bc7366dc9d69.PNG)
![kanboard2](https://cloud.githubusercontent.com/assets/15818492/17728480/b7e3f162-645f-11e6-9d20-b6a1fe5ef4d4.PNG)

**Comment by Chaosmeister** [comment] 2016-08-17 08:10
Ah now I understand your issue.  
Well that's just how the filter works.
It does not look for subtaskassignments yet if you filter for your assigned tasks.

**Comment by darkocobe** [comment] 2016-08-19 12:59
Yes that would be great because if you are looking only to the board you do not see if people assigned some sub-tasks for you and you do not work on them :)
Thanks

**Comment by dofl** [comment] 2016-10-05 13:17
We just updated our board and saw the same problem.

**Comment by fguillot** [comment] 2016-10-06 20:18
The filter `assignee` is only for tasks. However you can use the filter `subtask:assignee:"John Doe"` for subtasks.

**Comment by dofl** [comment] 2016-10-07 07:17
It isn't possible to use the filter in the board as 'status:open  assignee:"John doe" subtask:assignee:"John Doe" to show all tasks and subtasks for a member of the team on the board view. This was possible in the older versions and as we use this a lot it is a required functionality before we can upgrade to a newer version.

We'd tried to figure out which of the code is responsible for the board view's query, but we where unable to locate it. Can you tell where this is located so we can change this to our requirements and add it as a added functionality to kanboard?

**Comment by darkocobe** [comment] 2016-10-10 08:37
@fguillot with your proposal you can only see the sub-tasks. But still you can't see the sub-tasks and tasks at the same view. This was possible in the old version. Please create filter for both combined or give us other solution where we can configure how to view the open tasks and sub-tasks together.

**Comment by fabfri** [comment] 2016-11-10 09:25
I found out this post while I was searching if this behavior had been identified as a bug (since it worked in the previous version).
The opportunity to have a look simultaneously to my assigned task and subtasks is very used in our organization. Please add either the filter "allmytasks" or the possibility to have 'status:open assignee:"John doe" subtask:assignee:"John Doe"' (both subtask and task filters at the same time) as new improvement, as suggested by @darkocobe as well.

**Comment by jg-jhu-ds** [comment] 2016-12-28 22:32
This feature (to view tasks and subtasks at one time on the board) worked for me before version 1.0.31 as well.  Please add this as a bug to be fixed.

**Comment by ThomasTJdev** [comment] 2016-12-29 11:01
Agreed - the full overview of tasks and subtasks would be a great feature. We can't work without it since we often use multiple subtask within a task to visualize the progress for other team-members. 

For a temporary solution, we are using this hack to get around it: [SubtaskPluginHack](https://gitlab.com/ThomasTJ/KanboardSubtasksBoard)

**Comment by bugwatcher** [comment] 2018-02-12 02:22
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.

**Closed by bugwatcher** 2018-02-12 02:22 UTC
Labels: question
