### ISSUE TITLE
Project Sort Order

### ISSUE THREAD

**Issue by compumatter** [kanboard/kanboard#3575] opened 2017-11-27 03:15 UTC
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
No Ability To Sort Order By Projects Priority

### Expected behaviour
Would like to drag / drop or sort my Projects by order of their priority.  My projects are defined by my 'Clients' and the tasks within them rotate.  However sometimes it is very clear any project related to 'Client A' needs to be brought to the forefront. Not just a single task but that entire clients needs.

### Steps to reproduce
NA
![project-sortby](https://user-images.githubusercontent.com/121611/33249228-2c7447fa-d2de-11e7-9c6a-df602f42fb06.png)

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment] 2017-11-27 19:26
Why do you duplicate your own issue?

Duplicate of #3548

**Closed by fguillot** 2017-11-27 19:26 UTC
