### ISSUE TITLE
Custom Stylesheet limited to 255 chars

### ISSUE THREAD

**Issue by amurad** [kanboard/kanboard#2740] opened 2016-10-09 17:57 UTC
### Expected behaviour

Should be able to add custom stylesheet  of any length in Applications settings. 
### Actual behaviour

On save, I was constantly getting:

> Internal Error: SQL error

with no clue to what is wrong.

I finally figured out that in the database that field is limited to 255 chars, and therefore any custom styles added must fit within those limits.

That does not allow for much customization using custom css.
### Steps to reproduce
1. Go to /kanboard/?controller=ConfigController&action=application
2. Add custom stylesheet exceeding 255 chars
3. save
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: master
PHP version: 7.0.11
PHP SAPI: fpm-fcgi
OS version: Linux 4.7.2-1-ARCH
Database driver: mysql
Database version: 10.1.18-MariaDB
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.148 Safari/537.36 Vivaldi/1.5.627.3

**Comment by gramakri** [comment] 2016-11-18 09:36
@fguillot What is this issue a duplicate of?

**Comment by fguillot** [comment] 2016-11-29 22:46
@gramakri yes

Closing duplicate of #2701

**Closed by fguillot** 2016-11-29 22:46 UTC
Labels: duplicate
