### ISSUE TITLE
Bad tags list with Synology Docker graphical client (DSM6.0)

### ISSUE THREAD

**Issue by ogoudron** [kanboard/kanboard#2522] opened 2016-07-26 15:23 UTC
### Expected behaviour

I should be able to choose between "stable" or "latest" tags when choosing an image with the Synology Docker client.
### Actual behaviour

The tags are only : "centos7-dev", "precise-dev", "trusty-dev", "v1.0.29", "v1.0.29-hotfix1", "xenial-dev". 
### Configuration

Last DSM (DSM 6.0.1-7393 Update 2) on Synology DS216+.

![capture d ecran 2016-07-26 a 17 21 26](https://cloud.githubusercontent.com/assets/350129/17144011/a3ab3072-5355-11e6-840f-2598749e069d.png)

**Comment by fguillot** [comment] 2016-07-27 02:52
I don't know how your NAS is working but the tags are available on Docker Hub: https://hub.docker.com/r/kanboard/kanboard/tags/

**Comment by ogoudron** [comment] 2016-07-27 08:49
What is strange is that "stable" tag was available few weeks ago in Synology Docker client when i done my first test with Kanboard.
Now "stable" tag is not available on my NAS (DS216+) and on all my others NAS ( 3 x RS815+).

I don't think that there's a problem with your Docker configuration but maybe you done something concerning tags between the last time i tested it (v1.0.39) and now that trigger a bug somewhere at Docker HUB or at Synology Docker client.

Does something changed in the way you published your Docker tags since Kanboard 1.0.29 ?
Does the tags i see now have a signification for you ?

Thanks in advance.

**Comment by fguillot** [comment] 2016-07-27 22:49
I think there is some sort of caching on your NAS.

The cause of the problem is probably related to the fact that I moved the Github repository to the Kanboard organization. I also removed and recreated the Docker repository on Docker Hub because there is currently noway to update the source git repository for an automated build.

The tags you are seeing are the one available before I recreated the Docker repository.

**Comment by ogoudron** [comment] 2016-07-28 08:32
I mostly agree with this idea but i don't think that the NAS is caching something so i tested with a new NAS that was never configured for Docker.
I have installed the Synology Docker client on this fresh NAS and then when i select the Kanboar/Kanboard Image on the Docker Registry i have the same wrong list of tags. 

The bad news is that the problem may concern everybody trying to use Kanboard with Synology NAS and not only me.

**Comment by ogoudron** [comment] 2016-07-28 08:39
After reading some things about V1 / V2 Docker registry API can you check if your tags list is the same when using V1 and V2 API (personally i don't know how to do this test) ?

**Comment by ogoudron** [comment] 2016-07-28 09:12
Finally i was able to do the test and the V1 API does not show the right tags.
https://index.docker.io/v1/repositories/kanboard/kanboard/tags

The Synology Docker client still use the V1 API (not good but not a bug) and Docker Hub V1 API is buggy.

**Comment by fguillot** [comment] 2016-07-28 13:09
Interesting: https://github.com/docker/hub-feedback/issues/687

**Comment by kellenarb** [comment] 2016-08-26 03:51
Just to share a workaround, you can SSH into your synology and run:

`docker pull kanboard/kanboard:latest`

This will grab the latest tag for the Image and it will show up under "Image" in the Docker GUI.

**Comment by gpapin** [comment] 2016-10-04 09:16
The Synology docker client use the deprecated api v1 of the docker's registry. It might be why you don't get the results you expect. Best way to solve this is to get them to update their packet to use the api v2.

**Comment by fguillot** [comment] 2016-12-05 23:17
Closing this issue because I cannot do anything about it. Only Synology can do something...

**Closed by fguillot** 2016-12-05 23:17 UTC
Labels: question

**Comment by ssbarnea** [comment] 2017-01-12 21:51
This bug makes the entire Synology Docker application totally useless and it seems that the company completely ignores user feedback and still refuses to open a public issue tracker.
https://forum.synology.com/enu/viewtopic.php?f=258&t=126402&p=465716#p465716

**Comment by osaether** [comment] 2017-01-19 10:29
Synology released an updated version of Docker yesterday. Maybe this issue is fixed? Release notes here:
https://www.synology.com/en-us/releaseNote/Docker

**Comment by ssbarnea** [comment] 2017-01-19 10:49
I can confirm that their change (1.11.2-0270) fixed that issue, now we can download all tags.

As a funny note, they didn't even bothered to sort the list of tags alphabetically. On Jenkins images there is clear mess of tags but at least we can find the needle in it.

**Comment by ogoudron** [comment] 2017-01-19 10:52
Thanks for the news. I have tested again and it work now.
