### ISSUE TITLE
Kanboard doesn't give pretty URLs with define('ENABLE_URL_REWRITE', true)

### ISSUE THREAD

**Issue by n1trux** [kanboard/kanboard#4378] opened 2019-12-29 21:12 UTC
### Actual behaviour

The Docker-provided nginx can rewrite URLs but the URLs given by Kanboard do not look pretty.

### Expected behaviour

The links in Kanboard should look like the rewrite config in nginx.

### Steps to reproduce

Run the docker container.

Set `define('ENABLE_URL_REWRITE', true);`

### Environment
Version: v1.2.13
PHP Version: 7.3.11
PHP SAPI: fpm-fcgi
HTTP-Client: cURL
OS Version: Linux 4.19.0-6-amd64
Database: mysql 10.4.11-MariaDB-1:10.4.11+maria~bionic
Browser: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0

### related‽

#4079

**Comment by fguillot** [comment] 2020-01-06 04:54
Duplicate of #4079

**Closed by fguillot** 2020-01-06 04:54 UTC
