### ISSUE TITLE
The problem with using multibyte encodings

### ISSUE THREAD

**Issue by oksamitnyj** [kanboard/kanboard#2917] opened 2017-01-06 10:57 UTC
The problem with using multibyte character sets (Cyrillic): while maintaining the column names or in the name and description of the problem.
get an error "Internal Error: SQL error: SQLSTATE [22007]: Invalid datetime format: 1366 Incorrect string value: '\ x98 \ xD0 \ xB4 \ xD0 \ xB5 \ xD1 ...' for column 'title' at row 1". an example of the input line in the name of the task: «Идея»

### Configuration

Версия приложения: 1.0.36
Версия PHP: 5.5.38
PHP SAPI: apache2handler
Версия ОС: Linux 3.16.0-4-amd64
Драйвер базы данных mysql
Версия БД: 5.5.46-MariaDB
Браузер: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by fguillot** [comment] 2017-01-12 04:11
I'm not able to reproduce your issue, I tested with the same version of MariaDB and I can copy/paste any Cyrillic characters.

Can you check that the table tasks has the charset UTF-8? (`SHOW FULL COLUMNS FROM tasks;`) The column title should have utf8.

**Comment by fguillot** [comment] 2017-02-12 22:24
Closing this ticket because no answer.

**Closed by fguillot** 2017-02-12 22:24 UTC
Labels: waiting answer
