### ISSUE TITLE
users of 2 different board on the same host are logged in as another users

### ISSUE THREAD

**Issue by fourier** [kanboard/kanboard#2952] opened 2017-01-16 15:41 UTC
### Expected behaviour

Given the 2 installations of KB, for example
10.0.0.2/project1
10.0.0.2/project2

when the user is registered and logged in to both, he should be able to work independently

### Actual behaviour

The user is performing actions on project2 installation as someone else (another user of this project2 KB installation).

### Use case
For maintenance reasons on the same host we have 2 installations of KB board, one used for one project with multiple boards, and another is for another project with different multiple boards.

Sometimes users need to use both projects so they could be simultaneously logged in to both installations.
However the strange things start to happen: when the user start to create tasks/comment on second installation, he is identified as someone else. The only way to solve is to log out from both boards and login only to the second board installation.

I suspect the cookies/etc are bounded to ip address or URL; maybe better to use some unique kb installation id.

**Comment by fguillot** [comment] 2017-01-17 03:18
The session is managed by PHP itself. Kanboard doesn't do anything special except setting up the cookie parameters to the current directory.

Can you give more information about your installation because your example if ambiguous:

> Given the 2 installations of KB, for example
> 10.0.0.2/project1
> 10.0.0.2/project2

What is project1 and project2 for you? 2 different KB instances on the same domain?

**Comment by fourier** [comment] 2017-01-17 12:20
Hi,
Yes,
Project1 and Project2 are 2 different KB instances on a same domain. The configuration I use is:
```


    Application version: 1.0.36
    PHP version: 5.6.29-0+deb8u1
    PHP SAPI: apache2handler
    OS version: Linux 3.16.0-4-amd64
    Database driver: sqlite
    Database version: 3.8.7.1
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
```
But this issue was here from at least one year ago, I just never reported it.

**Comment by fguillot** [comment] 2017-01-18 02:34
I'm not really able to reproduce your issue. I installed 2 instances of Kanboard under the same domain on fresh ubuntu VM. The session cookies are correctly defined for each instance.

First instance installed at `http://mydomain/k1/`:

![cookie_instance2](https://cloud.githubusercontent.com/assets/323546/22048588/fec8f91e-dcfb-11e6-8afe-a5b4addc9dfb.png)

Second instance installed at `http://mydomain/k2/`:

![cookie_instance1](https://cloud.githubusercontent.com/assets/323546/22048589/fed6acda-dcfb-11e6-96b6-b05c7d626682.png)

I can use multiple sessions in the same browser window without any problem. Be logged as multiple users and I don't have any overlap.

Can you provide the same information to compare?

**Comment by fguillot** [comment] 2017-03-12 17:05
Closing because no answer.

**Closed by fguillot** 2017-03-12 17:05 UTC
Labels: server configuration, waiting answer
