### ISSUE TITLE
Make kanboard tickets exportable to PDF

### ISSUE THREAD

**Issue by noktork** [kanboard/kanboard#1492] opened 2015-11-24 14:39 UTC
Hello!
Once again I want to congratulate you on a explendid work with Kanboard!

The function I was thinking of is to download a ticket as PDF for external presentation and reporting.
My thought was to segment the ticket, at the top you should be able to see the creator/owner, opened date and other statistics. Next below that you should be presented with relation to other tickets. And the final section will have all comments done in the ticket.

**Comment by NinjaPewPew** [comment] 2016-02-07 10:26
:+1:

**Comment by fguillot** [comment] 2016-11-29 22:50
Duplicate of #2650

**Closed by fguillot** 2016-11-29 22:50 UTC
Labels: duplicate
