### ISSUE TITLE
Feature request: notify user task creation

### ISSUE THREAD

**Issue by Trapulo** [kanboard/kanboard#2793] opened 2016-11-02 07:58 UTC
Hi,
I'd like to send an email to a user when I create a new task and assign it to that user. It seems that currently emails are sent only when task are changed, not created (assigned). If this is not currently possible, it will be a great improvement.

thanks

**Comment by fguillot** [comment] 2017-02-19 14:24
Duplicate of #2746

**Closed by fguillot** 2017-02-19 14:24 UTC
Labels: duplicate
