### ISSUE TITLE
Allow All Users Access to Projects

### ISSUE THREAD

**Issue by rdnn** [kanboard/kanboard#3827] opened 2018-04-19 13:19 UTC
This issue is:

- [ ] Bug report
- [X] Feature request
- [ ] Improvement

- Please, read the [Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html).
- Ask questions on the [Forum](https://github.com/kanboard/forum/issues).

### Expected behaviour

It is desirable to have an option that allows all users access to projects without the need to add all users to a group and then add that group to a project. This feature would require additional SQL schema and a configuration option. However, this feature could be further enhanced by a plugin that modifies the SQL schema to enable all users to access projects by default.

**Comment by fguillot** [comment] 2018-04-19 17:31
Duplicate of #3570

**Closed by fguillot** 2018-04-19 17:31 UTC
