### ISSUE TITLE
JSON API getColumns need "manager" permissions

### ISSUE THREAD

**Issue by TheCloud** [kanboard/kanboard#2776] opened 2016-10-22 21:39 UTC
### Expected behaviour

We are using API to create a little mobile version and I noticed that getting the list of available columns didn't work with standard members while worked for project's managers and admins.
### Actual behaviour

If user login via API can list projects, tasks but can't list the columns in the project
### Steps to reproduce
1. Get getColumns with member credentials
   2.
   3.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: current 
- Database type and version: lite
- PHP version:
- OS:
- Browser:

**Comment by andresth** [comment] 2017-01-26 22:16
Hi,
I can confirm this bug.

In the file `app/Api/Procedure/ColumnProcedure.php` the function `getColumns` requests `ProjectAuthorization`. I guess it should be `ColumnAuthorization`. The function works as expected when I change it.

BTW the functions `removeColumn` and `updateColumn` only requires `ColumnAuthorization`. This means a normal user could delete or modify a column via the API. I don't think this is the intended behaviour.

Greetings Thomas

**Comment by fguillot** [comment] 2017-01-29 01:02
This is now fixed in v1.0.38

**Closed by fguillot** 2017-01-29 01:02 UTC
Labels: Fixed in dev, improvement
