### ISSUE TITLE
Keyboard Shortcut to Create New Task results in "Internal Error: Controller not found"

### ISSUE THREAD

**Issue by graffaelli** [kanboard/kanboard#3893] opened 2018-06-01 18:15 UTC
### Actual behaviour

1. In the board view, typing "n" to create a new task, the system displays the error "Internal Error: Controller not found". 
2. When using the Menu link to create a task, creation works as expected.

### Expected behaviour

1. In the board view, typing "n" should open the task creation window.

### Steps to reproduce

Logged in as user account and attempted typing "n" and the error appears.
Logged in as admin account and attempted typing "n" and the error appears.
Rebooted the server and the same issue. Note that this error did not appear when I was running version 1.2.3.

### Screenshots

![kanboard-controller-error](https://user-images.githubusercontent.com/10729482/40856445-c6a68de2-658c-11e8-97dc-61ad9b21ecd7.png)

### Configuration
- Kanboard version: 1.2.4
- PHP version: 7.0.28-0ubuntu0.16.04.1
- Server OS version: Linux 4.4.0-87-generic :: Ubuntu 16.04.1
- Database driver: sqlite
- Database version: 3.11.0
- Endpoint OS version: macOS 10.13.4
- Browser: Chrome 66.0.3359.181

**Comment by fguillot** [comment] 2018-06-05 19:02
I'm not able to reproduce your issue. Do you have any installed plugins? does all files copied correctly?

**Comment by graffaelli** [comment] 2018-06-05 19:33
I do have a few. I upgraded from 1.2.3 recently (which is when the issue occurred). I copied the /data and /plugins folder into the new installation. didn’t make any other changes. could a plugin cause such an issue?

On Jun 5, 2018, at 12:02 PM, Frédéric Guillot <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not able to reproduce your issue. Do you have any installed plugins? does all files copied correctly?

**Comment by fguillot** [comment] 2018-06-08 18:38
Ok so I'm closing this ticket. I let you find the faulty plugin and raise the issue to the plugin author.

**Closed by fguillot** 2018-06-08 18:38 UTC
Labels: unable to reproduce bug
