### ISSUE TITLE
project_activities table has invalid type "intege"

### ISSUE THREAD

**Issue by palica** [kanboard/kanboard#3162] opened 2017-03-28 20:50 UTC
I was trying to migrate from sqlite to postgres and this is one error that came up when running pgloader.

2017-03-28T20:33:36.596000Z ERROR Database error 42704: type "intege" does not exist
QUERY: CREATE TABLE project_activities
(
  id            bigint,
  date_creation bigint,
  event_name    text,
  creator_id    intege,
  project_id    bigint,
  task_id       bigint,
  data          text
);

-    Application version: 1.0.40
-    PHP version: 7.0.16
-    PHP SAPI: fpm-fcgi
-    OS version: FreeBSD 11.0-RELEASE-p8
-    Database driver: sqlite
-    Database version: 3.17.0
-    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by fguillot** [comment] 2017-03-29 00:04
Your problem is not related to Kanboard but to your migration from Sqlite to Postgres. The table structure that you copy and paste here might contains the answer to your question: `creator_id intege,`

**Comment by palica** [comment] 2017-03-29 06:18
This was using the sqlite file from my installation and I believe there is a typo here:

https://github.com/kanboard/kanboard/blob/master/app/Schema/Sqlite.php#L949-L962

**Comment by palica** [comment] 2017-03-29 06:36
created a pull request
https://github.com/kanboard/kanboard/pull/3163

**Comment by palica** [comment] 2017-03-29 06:55
and to fix existing tables this pull request
https://github.com/kanboard/kanboard/pull/3164

**Comment by palica** [comment] 2017-03-30 06:20
Frédéric, should I fix other tables for sqlite as well? They have left over columns that are making trouble when importing to postgres. 

Like tables: users (is_admin, is_project_admin), project_has_users, projects.

**Comment by fguillot** [comment] 2017-04-01 03:28
It's up to you. It was left as is because Sqlite is too limited for alter table.

Thanks for your pull-requests by the way :)

Closing this since you find the root cause of the problem.

**Closed by fguillot** 2017-04-01 03:28 UTC

**Comment by palica** [comment] 2017-04-01 19:54
I have trouble correcting the tables with php-pdo. When I run the command in sqlite3 I am able to rename and create new projects table without any issue, but I am not so successful with PDO. The problem is not being able to set "PRAGMA foreign_keys=off" for the transaction. Which ends up altering the REFERENCES to projects_bak and basically ruining the whole kanboard.

Do you maybe know how to do this correctly?

Here some code:
```
function version_115(PDO $pdo)
{
    $pdo->exec("
        PRAGMA foreign_keys=OFF
    ");
    $pdo->exec("
        CREATE TABLE new_projects (
           id INTEGER PRIMARY KEY,
           name TEXT NOCASE NOT NULL,
           is_active INTEGER DEFAULT 1,
           token TEXT,
           last_modified INTEGER DEFAULT 0,
           is_public INTEGER DEFAULT 0,
           is_private INTEGER DEFAULT 0,
           is_everybody_allowed INTEGER DEFAULT 0,
           description TEXT,
           identifier TEXT DEFAULT '',
           start_date TEXT DEFAULT '',
           end_date TEXT DEFAULT '',
           owner_id INTEGER DEFAULT 0,
           priority_default INTEGER DEFAULT 0,
           priority_start INTEGER DEFAULT 0,
           priority_end INTEGER DEFAULT 3,
           email TEXT
        )
    ");
    $pdo->exec("
        INSERT INTO new_projects SELECT id, name, is_active, token, last_modified,
          is_public, is_private, is_everybody_allowed, description, identifier,
          start_date, end_date, owner_id, priority_default, priority_start,
          priority_end, email FROM projects
    ");
    $pdo->exec("
        DROP TABLE projects
    ");
    $pdo->exec("
        ALTER TABLE new_projects RENAME TO projects
    ");
}

```

I've also tried putting it in one $pdo->exec , without success.
