### ISSUE TITLE
Mouseover tooltips are not disappearing

### ISSUE THREAD

**Issue by soudis** [kanboard/kanboard#3932] opened 2018-06-25 09:57 UTC
### Actual behaviour

When I hover of the subtasks or the description icons the subtasks or description appear in a tooltip, but they do not disappear until I move the mouse into the tooltip and then leave it again.

### Expected behaviour

The tooltip should disappear after I move the mouse away from the subtasks icon and not into the tooltip container. Otherwise it gets really annoying sometimes, if I just cross the subtasks icon accidentally by moving the mouse over the screen and suddenly somewhere a tooltip appears and stays indefinitely. 

This also blocks other tooltips from appearing. If I move the mouse to different description or subtasks icon, the tooltip is not appearing until i close the previous one by moving the cursor into the tooltip container and then leave it again.

### Steps to reproduce

1. Open any board containing cards with descriptions
2. Hover over the description icon on one of the cards
3. Move cursor away from the description icon and not into the tooltip
4. Tooltip stays indefinitely, blocking parts of the screen and blocks other tooltips from opening

### Screenshots

![kanboard tooltip](https://user-images.githubusercontent.com/16363411/41843714-87c5b9d2-786e-11e8-874f-59c9bd47af6a.png)

### Logs

no logs

### Configuration

- Kanboard version:  1.2.4
- Database type and version: 10.2.7-MariaDB-10.2.7+maria~jessie
- PHP version: 7.1.17
- OS: Ubuntu 16.04 LTS /  Linux 4.9.0-3-amd64
- Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by Victor-IT** [comment] 2018-06-25 19:36
v1.2.5
I have the same issue.

**Comment by Kantime** [comment] 2018-06-26 09:49
I'm complaining about this since 1.2.4
Please, do something !
**I returned to 1.2.3 just because of that issue.**

**Comment by jschuck** [comment] 2018-06-27 11:41
The issue was introduced with changeset 5996a8ab. The tooltips are not neccessarily opening up beneath the mouse cursor and are only closing on a mouseleave event. Which isn't happening unless you move the mouse over the tooltip.

That's what's causing this issue.

**Comment by neiaberau** [comment] 2018-06-27 22:48
I have the same issue, seen with Vivalidi Browser, Edge Browser
and I believe, this https://github.com/kanboard/kanboard/issues/3915 is about the same issue

**Comment by jschuck** [comment] 2018-07-13 13:35
I made some changes to the assets/js/core/tooltip.js and made a [patch](https://gist.github.com/jschuck/d760e19d66d366ce8bfe38e83ee7d6bd) for it. Works for me.

**Comment by Kantime** [comment] 2018-07-13 13:58
I only found these folders in 1.2.5:
assets/js/
No "core" folder
No "tooltip.js" file to update
If i create the core folder and copy you Patch in it, it doesn't work.
Thank's anyway 👍

**Comment by jschuck** [comment] 2018-07-13 14:12
That's because it's a source patch. You would need to patch the file in the source not in the installed version, install npm and gulp and minify the new javascript. That would get you the assets/js/app.min.js which you could put in your productive installation.

**Comment by Kantime** [comment] 2018-07-13 14:20
Okay, thank's for the explaination.
It will be too complicated for me, i'm just a user.
It would be great if your patch is applied to the next version of Kanboard :-)

**Comment by Kantime** [comment] 2018-11-10 22:10
v1.2.**6**
No evolution, same issue !

**Comment by neiaberau** [comment] 2019-03-04 19:52
still the same, no one lese having the issue?

**Comment by Kantime** [comment] 2019-04-06 20:47
v1.2.**9**
This problem is not resolved since 1.2.**3**
Is Frederic Guillot able to tell us if this will be resolved some day or not ? Many thank's

**Comment by nekohayo** [comment] 2019-08-01 19:14
Interestingly enough, this issue seems to be gone with the 1.2.10 release, I don't know what might have fixed it though (even when looking at the commits log), so this sounds too good to be true... can others confirm this is fixed?

**Comment by nekohayo** [comment] 2019-08-01 19:20
Ah nope, I spoke too soon, I got tricked by the fact that icons now react to hover correctly, and that the tooltips "seem" to be more reactive, but in practice the issue with tooltips not disappearing (unless you have put the mouse over them first) still remains.

**Comment by eSkiSo** [comment] 2019-08-22 11:21
The issue is that when you put the mouse on a tooltip icon but do not put the mouse on the actual tooltip it will not call the destroy event that is linked with mouse leaving tooltip area.

So at the moment tooltip is removed when:
- Mouse leaves actual tooltip
- You click anywhere else on the page

I've created a pull request to fix this.
With my changes the tooltip is removed when:
- Mouse leaves actual tooltip
- You click anywhere else on the page
- Mouse leaves parent (except when mouse is moved to the actual tooltip)

**Comment by fguillot** [comment] 2019-08-24 23:36
This issue should be fixed in v1.2.11.

**Closed by fguillot** 2019-08-24 23:36 UTC
