### ISSUE TITLE
Closing task from dropdown on board view - changed behaviour in 1.0.37?

### ISSUE THREAD

**Issue by mgrabow1** [kanboard/kanboard#2961] opened 2017-01-19 12:58 UTC
### Expected behaviour

Task is closed, green info on the board, KB stays on board view.
(it worked just like that in 1.0.36)

### Actual behaviour

Task is closed, but the view switched to task edit view.
(new in 1.0.37 after modal dialog handling change)

### Configuration

- Kanboard version: 1.0.37
- Browser: Chrome and Firefox.

**Comment by fguillot** [comment] 2017-01-24 02:19
This is a regression due to some refactoring, this is now fixed in the development branch. Thanks!

**Comment by fguillot** [comment] 2017-01-29 01:04
This is now fixed in v1.0.38

**Closed by fguillot** 2017-01-29 01:04 UTC
Labels: bug, Fixed in dev
