### ISSUE TITLE
Mandatory fields error when debugging active

### ISSUE THREAD

**Issue by fabryss** [kanboard/kanboard#2743] opened 2016-10-10 17:38 UTC
When active debugging in config file, and set it in "file", all the mandatory fields are not accepted.

When I delete config.php file, or simply disable debugging, everything back to work. 

Unfortunately I have a problem with smtp config, and I would understand with the debuging tool does not work, but unfortunately I can not even access. 

![screenhunter_379 oct 10 19 30](https://cloud.githubusercontent.com/assets/12843943/19245357/ea597bbc-8f20-11e6-872a-05f32e712fad.jpg)
![screenhunter_381 oct 10 19 30](https://cloud.githubusercontent.com/assets/12843943/19245356/ea54b906-8f20-11e6-9d30-033fc4bc49a0.jpg)
Thanks so much
- Kanboard version: 1.0.33
- Database type and version: sqlite
- PHP version: 7.0.11
- OS: Centos
- Browser: Chrome/Firefox/Explorer

**Comment by fguillot** [comment] 2016-11-14 14:44
What did you put in your config file?

**Comment by risturiz** [comment] 2016-12-16 03:44
I can confirm this

> 

    Application version: 1.0.35
    PHP version: 5.6.28-0+deb8u1
    PHP SAPI: fpm-fcgi
    OS version: Linux 2.6.32-44-pve
    Database driver: postgres
    Database version: 9.4.9
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

With debug:
- Cant login
- Cant create task

And actually i cant see why the email config dont work... What additional info do you need?

**Comment by risturiz** [comment] 2016-12-24 22:43
Ok, please confirm this... I have kanboard in subfolder -> www.domain.com/subfolder/ so i have to define path to debug.log:

`define('LOG_FILE', '/var/www/html/subfolder/data/debug.log');`

With this, the problem is solved and now e-mail works... You can close this bug :-)

**Comment by fguillot** [comment] 2017-01-15 14:09
@fabryss I cannot really reproduce this issue. I'm using the debug mode myself. Something is probably wrong is your config file. You should put a copy here to allow people to troubleshoot something. Thank you

**Closed by fguillot** 2017-01-15 14:09 UTC
Labels: unable to reproduce bug
