### ISSUE TITLE
Tag removed when moving task to another project

### ISSUE THREAD

**Issue by danj3** [kanboard/kanboard#4667] opened 2020-11-12 22:45 UTC
Version 1.2.15

### Actual behaviour

1. Tag a task
1. move task to another project
1. tag is removed

### Expected behaviour

1. Tag a task
1. move task to another project
1. tag remains

### Configuration

- Kanboard version: 1.2.15
- Database type and version: postgres/12.1
- PHP version: 7.3.11
- OS: Linux 3.10.0
- Browser: Mac Firefox

**Comment by fguillot** [comment] 2020-11-14 23:52
Duplicate of #4668

**Closed by fguillot** 2020-11-14 23:52 UTC
