### ISSUE TITLE
Feature Request: New Automatic Action - Disable Due Notification if Task is in certain Column

### ISSUE THREAD

**Issue by wucherpfennig** [kanboard/kanboard#3429] opened 2017-08-31 06:47 UTC
If you are working with task due dates and you have finished the task you move it to the eg. "Done" column. Although the task is temporarily "Done" the due notification is still sent to the user. Therefore the user needs to delete the due date on the task in order to not receiving daily / hourly notifications.

Therefore I am asking whether it would be possible to add a new "Automatic Action" to surpress this behaviour like: "Disable Notifications if task is in column X"

Best regards

wucherpfennig

**Comment by wucherpfennig** [comment] 2017-09-05 08:43
Please consider the "edge case" about sending notification if a task gets moved from one to the "Done" column in which case a notification should be sent. 

Once the task is in the column = no notifications.

best regards

wucherpfennig

**Comment by wucherpfennig** [comment] 2017-10-06 05:45
Suggestion for solution:

* Var A: Simple
  Add new action "Remove Due Date if moved to column X".
  * Pro: I think it is easy to implement. No additional edge cases and logic required (you do not need to think about what happens if a tickets get moved out of "Done" again whether the notification needs to be enabled or not
  * Con: You "loose" the information about the original due date. It is still available in the log I guess but if you move it out

* Var B: Complex
  Add new action "Disable Due Date Notification if moved to column X"
  * Pro: Solves the actual task
  * Con: Hard to implement since this behaviour rises multiple other issues like what happens to comments & ticket updates and so on. I do not know whether it is possible to suppress notifications partially whithout rewriting the hole notification system.

@fguillot any suggestions? I think I could write a PR for Var A. Feedback appreciated.

**Comment by fguillot** [comment] 2017-11-24 18:29
I don't believe that adding an automated action is the best approach. Adding a task status "open/completed" or a flag on the column to ignore the due date would be better.

This is a duplicate of #3099. Moving discussion to #3099.

**Closed by fguillot** 2017-11-24 18:29 UTC
Labels: feature request
