### ISSUE TITLE
Admin-Role gets overwritten

### ISSUE THREAD

**Issue by Patrock** [kanboard/kanboard#3307] opened 2017-06-20 12:28 UTC
Hello,

### Actual behaviour

i have a user both in Admin and Manager group (nested groups in LDAP). The admin role gets overwritten by manager role because manager group comes first in the foreach-loop of function getRole() in class Core/Ldap/User.php.

### Expected behaviour

Instead, the roles should be ordered by most rights so admin stays admin.
This could be achieved like this:

```php
protected function getRole(array $groupIds)
    {
        if (! $this->hasGroupsConfigured()) {
            return null;
        }
        $role = Role::APP_USER;
        foreach ($groupIds as $groupId) {
            $groupId = strtolower($groupId);
          
            if ($groupId === strtolower($this->getGroupAdminDn())) {
                $role = Role::APP_ADMIN;
            } elseif ($groupId === strtolower($this->getGroupManagerDn())) {
                if($role == Role::APP_USER)
                  $role = Role::APP_MANAGER;
            }
        }
          return $role;
        }
    }
```

### Steps to reproduce
1. put user in admin and manager group in LDAP
2. check user role after login
3. if role == admin -> rename entries so the order changes
4. try again -> role should now be manager

Thank you for this great tool,

Patrock

**Comment by psy-q** [comment] 2017-08-08 09:56
I'm seeing something similar but I'm not sure if it's the same. If a user is manually set to admin but is also in the group that is specified as manager group, the manager role will overwrite the admin role on login.

**Comment by psy-q** [comment] 2017-08-22 12:22
This is getting increasingly inconvenient for us, since even e.g. manager roles assigned to a user who logs in via LDAP are overwritten with normal user privileges the next time the user logs in.

**Comment by fguillot** [comment] 2018-03-08 21:23
PR #3734 has been merged, can you check if the problem is solved on your side?

**Closed** 2018-04-11 03:47 UTC
Labels: waiting answer
