### ISSUE TITLE
after deleting a project => i cannot make any more new projects 

### ISSUE THREAD

**Issue by dragontune** [kanboard/kanboard#2778] opened 2016-10-23 18:18 UTC
### Expected behaviour

I was experimenting with layout (collums and swimlanes, tags, tasks,...) in a project. 
I thought i was done testing, so i wanted to remove the project and start a new one. 
After deleting a project, i cannot make a new one. Even after refreshing the page or logging out and back in. 
### Actual behaviour

at the end of the deletionprocess i got an error (sql error)
Every time a make a new project (i see at the bottom a green bar that it's ok: your project has been made succesfully!)
but immediately after that, i get a big red bar on top:  Page not found / Sorry, I didn't find this information in my database! 
(the url of the page is: ?controller=ProjectViewController&action=show&project_id=4)
Nothing gets displayed.
### Steps to reproduce
1. make a few projects (i have 3)
2. delete one of them
3. try to make another one - it will fail
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
Application version: 1.0.34
PHP version: 5.5.36
PHP SAPI: fpm-fcgi
OS version: Linux 3.4.6
Database driver: sqlite
Database version: 3.4.1
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
```

**Comment by fguillot** [comment] 2017-06-03 22:53
Closing, unable to reproduce. Try again with a more recent version of KB.

**Closed by fguillot** 2017-06-03 22:53 UTC
Labels: unable to reproduce bug
