### ISSUE TITLE
Display Another Project field spans window

### ISSUE THREAD

**Issue by captainwasabi** [kanboard/kanboard#3935] opened 2018-06-26 22:45 UTC
### Actual behaviour
Display Another Project drop down spans window in Project Board display

### Expected behaviour
Display Another Product drop down is sized as in My Dashboard

### Steps to reproduce
Select a Project from the Dashboard

### Configuration

Application version: 1.2.5
PHP version: 7.0.30-0ubuntu0.16.04.1
PHP SAPI: apache2handler
OS version: Linux 4.4.0-128-generic
Database driver: mysql
Database version: 5.7.22-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by bugwatcher** [comment] 2018-10-03 00:35
Duplicate of #4005

**Closed by bugwatcher** 2018-10-03 00:35 UTC
