### ISSUE TITLE
Password restoration email URL is not a hyperlink

### ISSUE THREAD

**Issue by vitoyucepi** [kanboard/kanboard#4729] opened 2021-02-09 05:05 UTC
### Actual behaviour

```html
<p>To reset your password click on this link:</p>

<p>http://localhost/=
forgot-password/change/ea6e1fffe4945e2ff4eae4d4cf0eb52c4224bad171e481cf77e0f1=
099957c9</p>

<hr>
Kanboard
```

### Expected behaviour

```html
<p>To reset your password click on this link:</p>

<p>
  <a href="http://localhost/forgot-password/change/ea6e1fffe4945e2ff4eae4d4cf0eb52c4224bad171e481cf77e0f1099957c9">
    http://localhost/forgot-password/change/ea6e1fffe4945e2ff4eae4d4cf0eb52c4224bad171e481cf77e0f1099957c9
  </a>
</p>

<hr>
Kanboard
```

### Steps to reproduce

`docker-compose`:
```yml
version: "3.8"
services:
  web:
    image: "kanboard/kanboard:${KANBOARD_VERSION}"
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
    env_file:
      - postgres.env
      - kanboard.env
  db:
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - postgres.env
    environment:
      TZ: ${TZ}

volumes:
  kanboard_data: {}
  kanboard_plugins: {}
  kanboard_ssl: {}
  db_data: {}
```
`kanboard.env`
```env
MAIL_TRANSPORT="smtp"
MAIL_SMTP_HOSTNAME="${KANBOARD_SMTP_HOSTNAME}"
MAIL_SMTP_PORT="${KANBOARD_SMTP_PORT}"
MAIL_SMTP_USERNAME="${KANBOARD_SMTP_USERNAME}"
MAIL_SMTP_PASSWORD="${KANBOARD_SMTP_PASSWORD}"
MAIL_SMTP_ENCRYPTION="${KANBOARD_SMTP_ENCRYPTION}"
MAIL_CONFIGURATION="false"
MAIL_FROM="${KANBOARD_MAIL_FROM}"
```

1. Provide valid mail settings via env vars
1. Run with `docker-compose up`
1. Login with `admin:admin`
2. Set admin email address
3. Restore email address
4. Email is html but has no clickable link

### Configuration

- Kanboard version: v1.2.18
- Database type and version: postgres 13.1-alpine
- PHP version: 7.3 from alpine package repository
- OS: docker run on archlinux
- Browser: Chromium 88

**Comment by fguillot** [comment] 2021-02-22 04:38
Duplicate of #4728

**Closed by fguillot** 2021-02-22 04:38 UTC

**Comment by vitoyucepi** [comment] 2021-03-16 06:54
I somehow forgot about this issue. @fguillot is this really a dupe?

As far as I understand this problem was not originally meant to be the same as the other one.
This one is about template style.
The other one is about app variables guessing and docs.
