### ISSUE TITLE
Responsive Theme

### ISSUE THREAD

**Issue by hunopro** [kanboard/kanboard#2227] opened 2016-05-15 12:25 UTC
Hello,

I'm a new user of Kanboard, It's an amazing tool helping me to start my new business.
I got 2 associates whom are always on the roads and they use mobile a lot. Unfortunately impossible to follow clearly the project on a mobile browser with no responsive design.

Do you plan to make it responsive ?
Is there anybody start to work on this improvement ?
I would have done it myself if i was a programmer by i'm just a designer...

It's a very good idea to keep kanboard simple but would be great to give opportunity to the community to install their own theme (and share them) maybe this could help ?

Those are just some suggestions, i love your work and so great-full it's opensource. If my business goes well I could totally invest in some improvement on your software (by hiring a programmer for exemple). 

Thanks

**Comment by fguillot** [comment] 2016-05-17 01:37
Having a user interface that works on mobile devices is mandatory nowadays. However, I'm not sure yet if making the application responsive is the best way. A native mobile application is faster and have a better integration with the OS. Short answer, yes it's planned, just need time to do it.

**Comment by cmmata** [comment] 2016-05-17 08:58
I see there's already an [API](https://kanboard.net/documentation/api-json-rpc). So this should be as "simple" as build a native mobile app against that API. If time is the only problem here, you could start with a very simple project and specifications, mockups or anything, and accept PR of people building the rest of the app. I'm using kanboard and would like to have a mobile app, so could help with the Android / BB10 versions.

**Comment by hunopro** [comment] 2016-05-17 09:37
That's great !! If needed I could help with the UI design, even though there are plenty of free available template we could adapt.

**Comment by supportreq** [comment] 2016-06-15 13:18
@fguillot are v having the native apps soon?

**Comment by hubutz** [comment] 2016-07-05 05:14
@fguillot I agree, native apps would be fine. I'd been even willing to pay for that. As I'm no designer nor developer I can only help with testing. Would like to do that.

**Comment by TheCloud** [comment] 2016-08-20 05:20
IMHO, a web responsive UI rather than a native app has more luck to be available with less effort, less testing (each size, eatch device, each version of OS, localizatiom, distribution/ delivery via app-stores) and with all features quickly available rather than a native app.
Plus we don't know which super new device will be here in 2-3 years.
Also remember that via web UI, you develop once for all.

Native apps make sense when you have to work with information within the device, that is when security profile of web is not enough because you want to access user's data.
So if you need to access in RW mode to addressbook, calendar, images and device owner contents on the device, then app is the right choice.

If the issue is performance and speed, then a good caching of static contents really makes the difference.

So this was my 2 cents voting for web UI :-)

**Comment by hadiasghari** [comment] 2016-08-22 08:03
I'm evaluating a PM software for our team and Kanboard is at the top of the list -- with it's intuitive interface and many integrations. My only hesitation is that the UI is rather unusable on a smart-phone. Although I agree that a mobile app will be more elegant, making the web-UI responsive sounds like a quicker fix. I'd estimate integrating KB with a framework like bootstrap could be done in just days. That would greatly enhance the usability on most platforms, until the apps are ready. My 2 cents too :)

**Comment by aljawaid** [comment] 2016-08-22 11:17
Novice here, but could we not just add Bootstrap to it for the time being?

**Comment by fguillot** [comment] 2016-08-23 00:51
For you information, the current development version is more responsive than before. At least, this is usable on a smartphone.

All vanilla CSS have been moved SASS and the responsive stuff is handled by using SASS mixins.

**Comment by hubutz** [comment] 2016-08-23 09:11
Just to don't something foolish: if I want to try that out I'll go for a nightly build, right? I can just copy that over my existing folder and can come back to stable laters?

**Comment by fguillot** [comment] 2016-08-23 20:07
@hubutz use a separate installation to test the nightly build because the schema of the database can change.

**Comment by fguillot** [comment] 2016-09-08 14:30
The version 1.0.33 is now considered responsive so I close this ticket. There still a lot of improvements that can be done (dropdown menus for example) but at least this is possible to navigate in the application with a smartphone.

**Closed by fguillot** 2016-09-08 14:30 UTC
Labels: feature request

**Comment by cmmata** [comment] 2016-09-08 15:10
@fguillot Awesome!
