### ISSUE TITLE
Issue #1932 not fixed in current development version

### ISSUE THREAD

**Issue by sandromario** [kanboard/kanboard#3917] opened 2018-06-16 14:20 UTC
### Actual behaviour

The minimum height of swimlanes is still too large, resulting in empty swimlanes if there are few tasks. This issue was said to be fixed in #1932, but for me it is not.

### Expected behaviour

The swimlanes' height decreases if there are no or few tasks.

### Steps to reproduce

Collapse tasks and add an empty swimlane.

### Configuration

- Kanboard version: any
- PHP version: any
- OS: Linux
- Browser: Firefox

**Comment by fguillot** [comment] 2018-07-04 17:41
Duplicate of #3505

**Closed by fguillot** 2018-07-04 17:41 UTC
