### ISSUE TITLE
change select-dropdown-menu items to be links

### ISSUE THREAD

**Issue by n1trux** [kanboard/kanboard#3854] opened 2018-05-07 12:18 UTC
When I select the projects dropdown in the top right, the individual list entries are not links, so you can't right/middle click them and "open in new tab". Would be nice if I could do that.

Proposed change: make the list entries into `<a>` links.

**Comment by fguillot** [comment] 2018-05-07 17:19
Duplicate of #3366

**Closed by fguillot** 2018-05-07 17:19 UTC
