### ISSUE TITLE
TaskCompletionDateFilter don't work

### ISSUE THREAD

**Issue by pmcfernandes** [kanboard/kanboard#2958] opened 2017-01-18 18:38 UTC
### Actual behaviour

Completed filter don't work (app\Filter\TaskCompletionDateFilter.php)
### Steps to reproduce

On search put text like completed: >= 2017-01-01 and nothing happens

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: Master
- Database type and version: mysql
- PHP version: 5.6
- OS: WIndows
- Browser: Chrome

**Comment by markjszy** [comment] 2017-01-25 04:47
I was able to reproduce this in dev. I think it's just due to an absent configuration in the FilterProvider. Submitting PR shortly.

**Comment by fguillot** [comment] 2017-01-26 03:45
This is fixed by PR #2970

**Closed** 2017-01-26 03:44 UTC
Labels: bug, Fixed in dev
